### PR TITLE
cmd/tier: fix and document serve --addr

### LINKED ISSUE #112: FR: specify port for sidecar with `--port=N`
### What are you trying to do?

Since port 8080 might already be taken by some other service on the system, it would be useful to be able to specify the port to listen on for `tier serve`

### How should we solve this?

`tier serve --port=N` or something similar

### What is the impact of not solving this?

Just means nothing else can listen on port 8080.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bmizerany**
Fixes #112

### CODE REVIEW

File: cmd/tier/help.go [hunk 1]
```diff
@@ -143,7 +143,18 @@ Tier whois reports the Stripe customer ID for the provided org.
...
 	`tier`: errUsage.Error(),
+
+	`serve`: `Usage:
+
+	tier serve [--addr <addr>]
+
+Tier serve starts a web server that exposes the Tier API over HTTP listening on
+the provided service address.
+
+The default service address is "localhost:8080".
```
Comment (isaacs) [inline cmd/tier/help.go:156]: Hm, this is not accurate, the default address is `[::]:8080` (or `0.0.0.0:8080` if ipv4).

This is relevant, because specifying `--addr localhost:8080` means it won't respond on anything but the loopback.

Maybe it'd be better security-wise if the default really was `localhost:8080`?

Comment (bmizerany) [reply cmd/tier/help.go:156]: Agreed. Thank you for pointing this out. Easy fix.
