### PR TITLE
api: report 400 if plan or feature not found

### LINKED ISSUE #211: Internal Server Error when subscribing to plan that does not exist
### What is the issue?

```
$ tier subscribe org:o plan:doesnotexist@1
tier: httpError{status:500 code:"internal_error" message:"Internal Server Error"}
```

Expected more informative error, for example saying that the plan doesn't exist.

### Steps to reproduce

_No response_

### Are there any recent changes that introduced the issue?

_No response_

### OS

_No response_

### OS version

_No response_

### Tier version

0.6.2-dev20230104 tier commit: e4a653d8394bae2b6992eb4b303d71de074647ab-dirty

### PR DESCRIPTION
**Pull request by bmizerany**
Previously, the API would return a 500 if the user supplied a non-existent feature or plan.

There is more work to do on error reporting, but this commit provides clarity to the user with a clear error message.

Fixes #211

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -17,39 +18,62 @@ import (
...
 // HTTP Errors
-var errorLookup = map[error]error{
-	control.ErrOrgNotFound: &trweb.HTTPError{
+//
+// TERR1000: invalid requests
+// TERR1010: org or features problem
+// TERR2000: internal errors
+var errorLookup = map[error]*trweb.HTTPError{
+	control.ErrOrgNotFound: {
 		Status:  400,
```
Comment (isaacs) [inline api/api.go:42]: 400 is fine, but sort of feels like these "not found" errors should be 404s?

LGTM, just a bikeshed.

**Review by isaacs — APPROVED** [review]

File: api/api.go (hunk 1 above)
Comment (bmizerany) [reply api/api.go:42]: If I POST `/v1/schedule` it's a 400, and I think it should stay that, but we can change it to a 404 for `/v1/whoami` if it is not that way already.
